### ISSUE TITLE
パッケージの自動インストール

### ISSUE THREAD

**Issue by 515hikaru** [515hikaru/dotemacs#6]
`(package-install 'package-name)` などと書くことで自分がインストールしているパッケージの一覧を定義して、`git pull` して起動すれば自動でインストールされるようにしたい。

**Comment by mahito1594** [comment]
use-package.el を使っているみたいですが

```elisp
(use-package package-name
  :ensure t)
```

ではダメなのですか．
参考： https://jwiegley.github.io/use-package/keywords/#ensure-pin

**Comment by 515hikaru** [comment]
@mahito1594  ありがとうございます、まさに欲していた機能です(知りませんでした...)

**Comment by 515hikaru** [comment]
`:ensure t` を設定した。
